### ISSUE TITLE
Fix CORs issue with bus API

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-find-bus-operator#12]
Currently there is a CORS issue with the bus API on the live site.
Can the domains https://find-bus-operator.wmnetwork.co.uk and https://find-bus-company.wmnetwork.co.uk be added to the CORS allowed list.

Raise a CAB for this Thursday when done.

Speak to @houbly if any issues.

**Comment by houbly** [comment]
This has been fixed
